[tool.flake8]

extend-ignore = [
    # Styling rules already handled by black
    "E1",
    "W1",
    "E2",
    "W2",
    "E3",
    "W3",
    "E5",
    "W5",
    # No import at top of file: conflict with certain Data Science Packages
    "E402",
    #Docstring 
    "D100",
    "D104"
]

per-file-ignores = '''
    __init__.py:F401
'''

max-complexity = 10

docstring-convention = "google"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
preview = true
